repos:
  - repo: https://github.com/diffplug/spotless
    rev: v2.43.0
    hooks:
      - id: spotless-gradle
        entry: ./gradlew spotlessApply
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-jsonlint
    rev: v1.6.0
    hooks:
      - id: jsonlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/koalaman/shellcheck
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/gradle/wrapper-validation-action
    rev: v2.0.4
    hooks:
      - id: gradle-wrapper-validation
