
services:
  onnx-model:
    image: mcr.microsoft.com/onnxruntime/server:latest
    platform: linux/arm64/v8
    container_name: onnx-model
    command: ["sleep", "infinity"]
    volumes:
      - ./models:/models:rw
